### ISSUE TITLE
GUI Error? (Mac)

### ISSUE THREAD

**Issue by ItzKeneh** [bruvzg/gdsdecomp#101]
Hey there, I have a 2011 mac mini, version 10.13.6, not the best thing in the world but it's what I got for now. I downloaded the latest Godot re tools for mac. When it opens I am met with this (First Screenshot). So obviously I ran the command through the terminal and it does open. However, I am just stuck on a gray window (Screenshot 2). I assume it's because of my shitty mac, but I hope that's not the case and I can get this working! I would appreciate any help or confirmation that it's because of my mac. Let me know if you need more info!

![Screen Shot 2022-12-09 at 12 46 33 PM](https://user-images.githubusercontent.com/69255278/206761738-54180434-0565-4c93-a762-603160895e54.png)

![Screen Shot 2022-12-09 at 12 48 26 PM](https://user-images.githubusercontent.com/69255278/206762037-50234930-c14c-4131-aa0b-a5814f5236e8.png)

**Comment by nikitalita** [comment]
Unfortunately, your GPU is old enough that it doesn't run Vulkan, which is the default renderer for Godot 4. I think you might be able to run with the GLES renderer, but I am not sure if that's still an option for macOS. In a terminal, can you run `"Godot RE Tools.app\Contents\MacOS\Godot RE Tools" --help --verbose` and post the output here?

**Comment by nikitalita** [comment]
derp, it has the command line option to do that right there in the message box. Just try that.

**Comment by ItzKeneh** [comment]
> derp, it has the command line option to do that right there in the message box. Just try that.

I did do the command line option from the message box. As stated before, I am met with the gray box. 
As for the other command you sent this is what it returned.

![Screen Shot 2022-12-09 at 1 06 56 PM](https://user-images.githubusercontent.com/69255278/206765576-939d0d18-286d-45be-a053-71bac273965d.png)

**Comment by nikitalita** [comment]
try `"Godot RE Tools.app\Contents\MacOS\Godot RE Tools" --headless --help`.

**Comment by ItzKeneh** [comment]
![Screen Shot 2022-12-09 at 1 22 04 PM](https://user-images.githubusercontent.com/69255278/206767651-7bd24f86-71c3-4548-ad96-aaf0dace0dec.png)

**Comment by nikitalita** [comment]
Talking with one of the Godot devs, it appears that while Godot 4.x retains the opengl3 renderer, it's not guaranteed to work on macOS for all hardware (chalk it up to Apple's crappy OpenGL support). Unfortunately, it looks like that's the case here.

You can still run this as a CLI tool though, and it does everything that the GUI does: 
`"Godot RE Tools.app\Contents\MacOS\Godot RE Tools" --headless --recover=<game>.pck --output-dir=<output-dir>`

(make sure to include the `=` for the parameter values, this is a limitation of the godot cli parser)

**Comment by ItzKeneh** [comment]
THANKS! That was all I needed! You're a godsend!

**Comment by ItzKeneh** [comment]
Plot twist: I have a new pc and no longer use mac. Sorry.

**Comment by nikitalita** [comment]
Ah, well at least you've upgraded and can use the new Godot 4 vulkan features :)
