### ISSUE TITLE
cant interact with any button in menu

### ISSUE THREAD

**Issue by mrloco110** [bruvzg/gdsdecomp#103]

**Comment by nikitalita** [comment]
Gonna need some more info on this one, my dude. Can you please post your specs and OS version? A screenshot would also be nice (ctrl+alt+PrintScreen on linux and windows, cmd+shift+option+4 on macOS); just paste it directly into the message box.

**Comment by mrloco110** [comment]
when i open the program, if i try to interact with any menu button, nothing happens
![image](https://user-images.githubusercontent.com/26129311/206786107-3b90e4ea-d553-4f82-b75f-19f500f738c8.png)
after i click in the ok button, nothing else works
![image](https://user-images.githubusercontent.com/26129311/206786186-7af5a37c-0ff7-454a-a5b7-2c5dbbaf1fe2.png)

**Comment by nikitalita** [comment]
Do you have any other processes that are stealing focus? If so, try closing them.

If this doesn't work, I'm going to be pushing a new release shortly that might address this, and you can try that. In the meantime, you can try running it as a CLI tool, see the README: https://github.com/bruvzg/gdsdecomp#command-line

**Comment by nikitalita** [comment]
Try running the standalone artifact here to see if this fixes your issue: https://github.com/bruvzg/gdsdecomp/actions/runs/3666183733
