### ISSUE TITLE
Is it possible to decompile .gde scripts with or without the encryption key?

### ISSUE THREAD

**Issue by PlayCubern** [bruvzg/gdsdecomp#109]
Is it possible?

**Comment by nikitalita** [comment]
Yes, there’s an option in the RE Tools dropdown to set the key. You have to provide the decryption key yourself. We do not provide means to recover the key.

**Comment by OoIks** [comment]
> Yes, there’s an option in the RE Tools dropdown to set the key. You have to provide the decryption key yourself. We do not provide means to recover the key.

What if you dont have the key? I saw a issue which stated that RE Tools was decompiling encrypted scripts

**Comment by nikitalita** [comment]
> > Yes, there’s an option in the RE Tools dropdown to set the key. You have to provide the decryption key yourself. We do not provide means to recover the key.
> 
> What if you dont have the key? I saw a issue which stated that RE Tools was decompiling encrypted scripts

then you'll have to find some means of recovering it. We don't provide instructions on how to do that, although it is possible. You could look in the Godot source code for how it stores the key in the PAK.

**Comment by OoIks** [comment]
> 

I did see the godot source code on how it stores the key in exe. It just adds it to a random location in the .exe's binary, I also saw bruvzg's comment on godot's official repository on how easy it is to decrypt it using a disassembler
