### ISSUE TITLE
Convert stream textures to PNG not working

### ISSUE THREAD

**Issue by Azagwen** [bruvzg/gdsdecomp#110]
### System information

Windows 10, Nvidia GTX 1080

### Issue description

Passing exported `.stex` files in the `Convert stream textures to PNG` dialog results in the following error message and no output image:

```
-2023-01-06-04-01-24 [Convert textures]: converting G:/Draws/Project_game/GDRE_tools-v0.4.8-windows/INPUT6/.import/1_21.tga-1040131b52fee10d7ff350bd4ba77925.s3tc.stex
USER ERROR: Transient parent has another exclusive child.
   at: Window::set_visible (scene\main\window.cpp:685)
-2023-01-06-04-01-24 [Convert textures]: 
-2023-01-06-04-01-24       G:/Draws/Project_game/GDRE_tools-v0.4.8-windows/INPUT6/.import/1_21.tga-1040131b52fee10d7ff350bd4ba77925.s3tc.stex (write error)
-2023-01-06-04-01-24       
-2023-01-06-04-01-24 [Convert textures]: At least one error was detected!
USER ERROR: Condition "source_image->is_compressed()" is true. Returning: FAILED
   at: PNGDriverCommon::image_to_png (drivers\png\png_driver_common.cpp:134)
USER ERROR: Can't convert image to PNG.
   at: ResourceSaverPNG::save_image (drivers\png\resource_saver_png.cpp:54)
USER ERROR: Transient parent has another exclusive child.
   at: Window::set_visible (scene\main\window.cpp:685)
```

The `.stex` file that gave me this error is from the game `INPUT6` which is made with Godot v3.5.1

### Steps to reproduce

- recover project (INPUT6, no other project was tried)
- grab any `.stex` file from `.import`
- pass it through the `Convert stream textures to PNG` dialog
- get error

### Recovery log

[gdre_export.log](https://github.com/bruvzg/gdsdecomp/files/10357336/gdre_export.log)

**Comment by nikitalita** [comment]
Ah yeah, here’s the problem:
```
USER WARNING: Decompression not implemented yet for texture format DXT1 RGB8
```
Some of the texture formats in godot don’t actually have decompression support built into godot, so we can’t decompress and convert them. I’ve been bugging the devs about this, but it’s low priority right now.

**Comment by Azagwen** [comment]
Aw, that's too bad :(
Thanks for the reply tho! Looking forward to it if it ever gets implemented

**Comment by AlexeyGrishin** [comment]
Is there any workaround, to somehow get image in any format from such stex file?

**Comment by nikitalita** [comment]
> Is there any workaround, to somehow get image in any format from such stex file?

You could modify gdsdecomp to dump the raw image data from the texture, which would be in its original format (in the case of the example above, DXT1 RGB8).

**Comment by Lock-The-Door** [comment]
I just tried building from source and it looks like it's able to successfully decompress DXTs. I looked at the commit history and the function that's used for decompression has supported DXT decompression for years.
I believe the actual reason for this issue is because the of the `module_squish_enabled=no` found in the github action since godot uses the squish library to decompress DXT files, resulting in a compiled version without DXT support.

**Comment by nikitalita** [comment]
I test locally with all the modules enabled; I had looked into this a while back, and the main problem was that the squish version they were using at the time had all the decompression support ripped out, so it was pointless to include it. I guess they fixed that?
