### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Raffa064** [bruvzg/gdsdecomp#111]
I'm making a game in godot mobile version... but a problem has deleted all the files of my phone and I have only the project exported apk file.. inside  it has the scrips with gdc file extension... can you help me for recover? i don't have computer to use your tool..... please help me!!!!!!!!!!!!!!

**Comment by nikitalita** [comment]
Attach your game here and maybe someone can help you.

**Comment by nikitalita** [comment]
Also, how did you create this game in the first place if you don’t have a computer?
