### ISSUE TITLE
USER ERROR: Index p_index = 0 is out of bounds (size() = 0).

### ISSUE THREAD

**Issue by seamcker** [bruvzg/gdsdecomp#114]
### System information

Windows10 NVIDIA - NVIDIA GeForce GT 740

### Issue description

Hello Dear Author,It was normal for me to use it before, but when I opened a new pck file today, an error occurred and it could not be parsed:
    Opening file: F:/Test/GDRE_tools-v0.4.8-windows/test.pck
USER ERROR: Index p_index = 0 is out of bounds (size() = 0).
   at: CowData<class String>::get (.\core/templates/cowdata.h:155)

Thank you for your great job.

### Recovery log

Godot Engine v4.0.beta.custom_build.ae86d907e - https://godotengine.org
Vulkan API 1.2.175 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GT 740
 
Opening file: F:/Test/GDRE_tools-v0.4.8-windows/test.pck
USER ERROR: Index p_index = 0 is out of bounds (size() = 0).
   at: CowData<class String>::get (.\core/templates/cowdata.h:155)

**Comment by nikitalita** [comment]
By a new pck file, you mean one created without any assets in it? 

What did you use to create it? Can you please attach it here?

**Comment by cgsdev0** [comment]
I have a PCK file that also produces this error, which was built with Godot 4.0.2

https://github.com/cgsdev0/ldg-jam-2023/suites/12198636664/artifacts/644440425

**Comment by nikitalita** [comment]
Ack, it looks like Godot 4.0.2 has started stripping out both the [deps] and [params] section from the .import files upon export. I'll push a fix momentarily.

**Comment by nikitalita** [comment]
When the CI finishes building, can you give this a shot and see if it works for you? https://github.com/bruvzg/gdsdecomp/actions/runs/4686113567

**Comment by cgsdev0** [comment]
it works! 🎉

**Comment by nikitalita** [comment]
Fixed in latest release.
