### ISSUE TITLE
Some scenes with external resources are partially converted

### ISSUE THREAD

**Issue by deltahgs** [bruvzg/gdsdecomp#119]
### System information

Fedora 37

### Issue description

Hi, 
First thanks for this tool, it helps a lot :raised_hands: 
I'm encountering an issue while decompiling a project.
Some .tscn files end up with only the resource definitions, ex:
```
[gd_scene load_steps=2 format=2]
[ext_resource path="res://path/to/script.cs" type="Script" id=1]
```
causing godot to crash with some EOF error
The script does exist in that location. Looking at the relative x.tscn.converted.res files, there is mode data like the node styling (anchor_right, margin_top etc) so my guess would be that we're losing the node when converting from binary to text

I'm joining an example of a binary with the text version, do you have an idea of what may be going wrong ? 

Thanks :pray: 

[scene.zip](https://github.com/bruvzg/gdsdecomp/files/11070240/scene.zip)

### Recovery log

[gdre_export.log](https://github.com/bruvzg/gdsdecomp/files/11070249/gdre_export.log)

**Comment by deltahgs** [comment]
btw are .converted.res files supposed to be kept ? on another project (where decompression worked) they are none in the results

**Comment by nikitalita** [comment]
Hmmm, this is interesting, this seems to be a Godot 3.x mono game with .cs files used for the scenes and they're autoconverted to binary RESOURCES upon export, not binary scenes. I haven't encountered anything like this in the wild. Can you please hit me up on Discord to discuss further? My username is nikita_lita on there.

**Comment by nikitalita** [comment]
to clarify, I was referring to the Godot discord, which is here: https://discord.gg/CUSuf69u
