### ISSUE TITLE
Error while building on Linux with 3.2

### ISSUE THREAD

**Issue by esmeraldaliaj** [bruvzg/gdsdecomp#13]
Following the instructions I get this error when building with the 3.2 branch of Godot.

```
modules/gdsdecomp/register_types.cpp:6:10: fatal error: core/object/class_db.h: No such file or directory
    6 | #include "core/object/class_db.h"
```

Building on the `master` branch produces another String related error that I do not think has anything to do with `gdsdecomp`

**Comment by bruvzg** [comment]
Which branch of `gdsdecomp` are you using, `3.2` is for Godot `3.2`, `master` is for Godot `4` (but it was not updated for some time since there is no bytecode for the new version of GDScript).

**Comment by esmeraldaliaj** [comment]
And you are obviously correct, I was using the wrong combination of versions.
