### ISSUE TITLE
Just add "unpack.bat" with the single line "gdre_tools.exe --recover=Brotato.pck"

### ISSUE THREAD

**Issue by LockMan007** [bruvzg/gdsdecomp#131]
### Resource Type

Just add "unpack.bat" with the single line "gdre_tools.exe --recover=Brotato.pck"

### Describe the problem or limitation you are having

Just add "unpack.bat" with the single line "gdre_tools.exe --recover=Brotato.pck"

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Just add "unpack.bat" with the single line "gdre_tools.exe --recover=Brotato.pck"

**Comment by nikitalita** [comment]
No.
