### ISSUE TITLE
Can you recreate the .exe directly?

### ISSUE THREAD

**Issue by Saipan0** [bruvzg/gdsdecomp#134]
hi, thanks for your work. I wanted to ask if there is a way to recreate a .exe executable of a game?
some games i've seen, they only have the .exe file, i extract it and translate the texts. Then would it be possible to recreate the exe?
Or is there some way to create some sort of "patch.pck" for the changes to work?
thanks a lot for your work.

**Comment by nikitalita** [comment]
No, but I believe PckExplorer has this capability.

**Comment by Saipan0** [comment]
> No, but I believe PckExplorer has this capability.

OK thank you. i will try to see.
