### ISSUE TITLE
script decompiler isn't working

### ISSUE THREAD

**Issue by thequeenbea** [bruvzg/gdsdecomp#135]
### System information

Debian 11

### Issue description

any time i try to decompile a .gde file with the latest bytecode version, i get this error:
/path/to/file (Encryption Error)

### Steps to reproduce

not exactly sure, i just try decompiling and it throws an error

### Recovery log

[gdre_export.log](https://github.com/bruvzg/gdsdecomp/files/11581030/gdre_export.log)

### Minimal reproduction project

scrabdackle: https://store.steampowered.com/app/1578720/Scrabdackle/
discord tag: queenbea#7979

**Comment by nikitalita** [comment]
GDE files are encrypted. You need to retrieve the encryption key and set the decryption key in the settings in order to decompile them. We don't provide instructions on how to retrieve the encryption key.
