### ISSUE TITLE
Application not running

### ISSUE THREAD

**Issue by Cool-Dude-Fab** [bruvzg/gdsdecomp#141]
### System information

VM Windows 11 from Mac M2 (parrallels)

### Issue description

Hello, I am trying to use Godot RE Tools to extract the YOMI hustle files so that I can begin modding. I am not a tech pro but I am not a noob either. However, before I can even begin to start modding characters, I already have encountered an issue. Whenever I try to run Godot RE Tools (literally the first step into modding), the application does not open properly. It gets stuck on the "Legal Notice" window but that doesnt respond and results in the application force quitting. I have attached an image of what happens. Pressing Enter makes the legal notice window dissappear- however the main application is still greyed out and unresponsive. I have had my fair share of bad luck but something not working before the beggining step is a first for me. Any help would be appreciated. I would like to point out that my brother has the exact same laptop with the exact same softwares with the exact same specs and exact same versions and it works perfectly fine for him. So I am unsure as to why it is not working for me. If I need to give any further information, please let me know.

![image](https://github.com/bruvzg/gdsdecomp/assets/31155026/68ac1df9-0233-488e-a505-7c33ae5ad3fb)

### Steps to reproduce

1. Download GDRE Tools v.0.5.3
2. Extract files
3. Open gdre_tools
4. Unresponsive

### Recovery log

N/A

**Comment by nikitalita** [comment]
Don't use the windows version. Use the native mac version: https://github.com/bruvzg/gdsdecomp/releases/tag/v0.5.3
