### ISSUE TITLE
Not working in a virtual machine

### ISSUE THREAD

**Issue by henryernice** [bruvzg/gdsdecomp#142]
### System information

MacOS 13.3.1 running Windows 11 in Paralells desktop. 

### Issue description

I know this is not your main concern but is it a bug or is there anything i can do? 
And the reason i have to use this in a virtual machine is because i am trying to mod Brotato which is a windows game.
And it is on an M1 Macbook pro so its hard to reproduce. Sorry

### Recovery log

N/A

**Comment by nikitalita** [comment]
Yeah, I just tested it, it's not able to work in GUI mode because the shaders can't compile (Parallels likely doesn't have support for compiling GLES3 headers with their virtual GPU). 

For a workaround, use it in CLI mode, see the README here: https://github.com/bruvzg/gdsdecomp#command-line

**Comment by henryernice** [comment]
Thanks Im gonna try that :)

**Comment by henryernice** [comment]
I am now trying it but when i try to recover Brotato i get this error message.

gdre_tools : The term 'gdre_tools' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ gdre_tools --headless --recover="C:\Program Files (x86)\Steam\steamap ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (gdre_tools:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
