### ISSUE TITLE
Failed to recover pck in 0.5.3 and failed to decompile .gde file

### ISSUE THREAD

**Issue by 2717753650** [bruvzg/gdsdecomp#145]
### System information

N/A

### Issue description

1.Failed to recover a game package of Godot version 2.1 using 0.5.3, but successful using 0.5.2.
2.Failed to decompile .gde file with the key. Error log:
  2.1.Condition "p_base->get_length() < base + length" is true. Returning: 
       ERR_FILE_CORRUPT.
  2.2.Condition "err" is true. Returning: ERR_FILE_CORRUPT.

### Recovery log

N/A

**Comment by nikitalita** [comment]
2.1? Are you sure you didn't mean 3.1? If that is the case, then I think I know what the issue was. Which PCK were you trying to decompile?
