### ISSUE TITLE
Can't restore ctex png files?

### ISSUE THREAD

**Issue by Badestrand** [bruvzg/gdsdecomp#147]
### System information

macOS 13.2.1, Apple M1 Pro, opengl3

### Issue description

When choosing a ctex of a compressed png I get an error, see below in the recovery log.

Is this not supported yet? Then a hint in the README would be great.

### Recovery log

USER ERROR: Condition "source_image->is_compressed()" is true. Returning: FAILED
   at: image_to_png (drivers/png/png_driver_common.cpp:134)
USER ERROR: Can't convert image to PNG.
   at: save_image (drivers/png/resource_saver_png.cpp:54)
USER ERROR: Transient parent has another exclusive child.
   at: set_visible (scene/main/window.cpp:747)

**Comment by nikitalita** [comment]
I need the full log to fully diagnose the problem; however, I think we may have just fixed the issue, can you give the artifacts here a try to see if this fixes it: Can you try the artifacts here to see if this fixes the problem?https://github.com/bruvzg/gdsdecomp/actions/runs/7081095677?pr=150#artifacts
