### ISSUE TITLE
Decompiled game cannot be compiled again

### ISSUE THREAD

**Issue by otDan** [bruvzg/gdsdecomp#149]
### System information

Windows 11

### Issue description

Whenever exporting to any platform I get spammed these two lines over and over again, the compiled game does not run but the in editor game runs fine.

ERROR: Cannot erase nonexistent section "deps".
   at: (core/io/config_file.cpp:120)
ERROR: Cannot erase nonexistent section "params".
   at: (core/io/config_file.cpp:120)

### Steps to reproduce

- Decompile Megaloot Demo from Steam
- Open the project
- Build the project in debug mode for any platforms
- Look at the console output

### Recovery log

[gdre_export.log](https://github.com/bruvzg/gdsdecomp/files/13299387/gdre_export.log)

**Comment by otDan** [comment]
if you need a more direct way to test this feel free to answer me in the godot modding discord or just dm me directly at @otDan

**Comment by nikitalita** [comment]
fixed in #151
