### ISSUE TITLE
 Decompression not implemented yet for texture format BPTC_RGBA (png)

### ISSUE THREAD

**Issue by MichaelWengren** [bruvzg/gdsdecomp#156]
### Resource Type

PNG texture. Decompression not implemented yet for texture format BPTC_RGBA

### Describe the problem or limitation you are having

This is just a png texture, can this be implemented by changing engine settings?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

-

**Comment by nikitalita** [comment]
Yeah, this is one of the textures whose modules do not have decompression support. I've bugged the devs about readding that, but there's nothing I can do about fixing that right now.
