### ISSUE TITLE
Unpack project.binary

### ISSUE THREAD

**Issue by esmeraldaliaj** [bruvzg/gdsdecomp#16]
Can the project.binary file be decompiled also? If not then this could be an enhancement idea. 
I've forgotten my "pixel perfect" settings that I made 3 years ago and would be nice to also be able to do that.

**Comment by nikitalita** [comment]
yep, I'm doing that on my fork.

**Comment by 344389541** [comment]
> yep, I'm doing that on my fork.
> https://github.com/nikitalita/gdsdecomp/tree/3.2-cli-stuff
> just unpack the pak/exe and it will do that automatically

Has the binary been uploaded?

**Comment by nikitalita** [comment]
its since been merged in here. There are no binaries, you have to compile it yourself.

**Comment by nikitalita** [comment]
> it produced **godot.windows.opt.64.exe** which couldn't be run because it was missing the *.pck file. How do I create that for gdsdecomp?

You have to compile both the editor and the template, then export the standalone project using the editor.

Just use the standalone version on `master` here:
https://github.com/nikitalita/gdsdecomp/actions/runs/1339048875
