### ISSUE TITLE
Arrays are all empty

### ISSUE THREAD

**Issue by wolfsmith520-github** [bruvzg/gdsdecomp#161]
### System information

Windows 11, Intel i7-12650H, RTX 4070 Laptop

### Issue description

The arrays in the decompiled project are all empty, which break the entire code base. In small project I can just drag them myself, but in big project, this process is annoying,
![image](https://github.com/bruvzg/gdsdecomp/assets/67470569/5b9e2123-11f2-4dbb-845e-8f57c1d92d91)

### Recovery log

[gdre_export.log](https://github.com/bruvzg/gdsdecomp/files/13925805/gdre_export.log)

**Comment by nikitalita** [comment]
I JUST fixed this on master, but I have not yet tagged a new release. I'll tag a new release in about an hour.
