### ISSUE TITLE
Error: Couldn't load project data at path ".". Is the .pck file missing?

### ISSUE THREAD

**Issue by manjaroman2** [bruvzg/gdsdecomp#165]
### System information

Arch Linux

### Issue description

I cloned the godot repo at the specified commit. Then I cloned the gdsdecomp repo inside of the modules folder. 

I used this command to compile:
`scons platform=linuxbsd use_llvm=yes linker=lld use_static_cpp=no target=template_debug`

This command should recover the game, I have [GAME].pck and [GAME].exe in the root folder of the godot repo:
`bin/godot.linuxbsd.template_debug.x86_64.llvm --headless --path=modules/gdsdecomp/standalone --recover=[GAME].pck`

I tried compiling with:
scons platform=linuxbsd target=template_debug

And running:
bin/godot.linuxbsd.template_debug.x86_64 --path=modules/gdsdecomp/standalone

In both cases, I get this error:
Error: Couldn't load project data at path ".". Is the .pck file missing?

### Recovery log

N/A

**Comment by nikitalita** [comment]
did you prefix `game.pck` with `./`?
