### ISSUE TITLE
The game "KinitoPET" on steam doesn't decompile properly and has 100 errors on launch. (Note that the game relies on Godot Steam a fork of Godot, the game is running on Godot version 3.3.3) the game crashes upon attempting to run due to errors created by gdsdecomp.

### ISSUE THREAD

**Issue by PeaceDevWasTaken** [bruvzg/gdsdecomp#166]
I'm trying to mod this game, I don't want to beg the dev for the source code, so I'd figured I'd use this tool on my copy of the game but it opens with a bunch of warnings and errors.

Do you think you could look into what's causing the issues? The game is mentioning a lot of warnings and has a lot of errors, which I'm not sure what any of them mean. If I can get an example of these errors later when I'm free, I will try to share it.

**Comment by nikitalita** [comment]
I need the GDRE log. It should be in the output folder where you attempted to extract it to.

**Comment by music-discussion** [comment]
> I need the GDRE log. It should be in the output folder where you attempted to extract it to.

I don't think they are responding to this issue but here is my log file when attempting to export.
[gdre_export.log](https://github.com/bruvzg/gdsdecomp/files/14188377/gdre_export.log)

**Comment by nikitalita** [comment]
Yeah, that's normal output. Meshes and Godot 3.x Scenes aren't supported for export yet, and it's just reporting which resources it can't export. I should probably change that warning message so that it only outputs when `--verbose` is passed.
