### ISSUE TITLE
Error when decompiling gde files

### ISSUE THREAD

**Issue by jeuxdevilains** [bruvzg/gdsdecomp#170]
### System information

Windows 10

### Issue description

After having successfully extracted the contents of a pkg (v. 3.5.3), I try to decompile gde files, using 3.5.0 script bytecode version. Unfortunately, the process fails and the console displays this:
USER ERROR: Condition "p_key.size() != 32" is true. Returning: ERR_INVALID_PARAMETER
   at: FileAccessEncryptedv3::open_and_parse (modules\gdsdecomp\compat\file_access_encrypted_v3.cpp:41)
USER ERROR: Condition "err != OK" is true. Returning: ERR_UNAUTHORIZED
   at: GDScriptDecomp::get_buffer_encrypted (modules\gdsdecomp\bytecode\bytecode_base.cpp:201)
USER ERROR: Encryption Error
   at: GDScriptDecomp::decompile_byte_code_encrypted (modules\gdsdecomp\bytecode\bytecode_base.cpp:173)

### Recovery log

N/A

### Minimal reproduction project

Discord: vilainjoueur

**Comment by nikitalita** [comment]
It’s an encryption error. You need to provide the key. We won’t tell you how to recover it, but it is possible.

**Comment by jeuxdevilains** [comment]
Thank you! For some reason, I thought the key was needed to even extract the files and since it was succesful, I didn't expect errors when decompiling. The issue is resolved.
