### ISSUE TITLE
godot 2.1.7 looks like not support

### ISSUE THREAD

**Issue by triplekill** [bruvzg/gdsdecomp#171]
### System information

Windows 11, gefoucs 3060

### Issue description

When I open a Godot 2.1.7 version GDE file, the program automatically crashes and exits.

### Recovery log

"N/A"

**Comment by nikitalita** [comment]
wait, they actually released 2.1.7?

**Comment by nikitalita** [comment]
No, they didn't, which means that this is a game working from a custom build on the 2.1 branch. Which game is this from?

**Comment by triplekill** [comment]
yes, its an self build version.
this ticket may closed

**Comment by nikitalita** [comment]
Did you get it to work?

**Comment by triplekill** [comment]
yes, the self build version change encrpty key algorithm ，xor 0x37
