### ISSUE TITLE
Exporting Buckshot Roulette v1.2.2, getting weird issue when exporting.

### ISSUE THREAD

**Issue by thecatontheceiling** [bruvzg/gdsdecomp#173]
### System information

Windows 10

### Issue description

I am using the latest version of gdsdecomp (same issue happens with latest nightly build with experimental scene exporting) and I have a weird issue where when I try to compile it. It does compile fine using the template I give it but apparently the game fails to find a certain .ctex file even though it is there in .godot/imported:

![image](https://github.com/bruvzg/gdsdecomp/assets/75037904/ba90bbdc-6d5f-4012-895c-4c19968d07b6)

running the project in the editor doesn't cause this issue to happen

any help would be appreciated! 

### Steps to reproduce

1. Decompile Buckshot Roulette
2. Compile it
3. Run compiled game with cmd (cd gamedirectory & buckshotroulette.exe, no extra arguments)
4. Look at cmd when you press "start" on the main menu, will say it can't load image
5. Go into the room with the dealer and observe health counts, they will look like green rectanges.

### Recovery log

[gdre_export.log](https://github.com/bruvzg/gdsdecomp/files/15209366/gdre_export.log)

**Comment by nikitalita** [comment]
Not sure; nothing shows up in the logs regarding that file. This may be a bug in the game. Try running the retail game and check the logs for that.

**Comment by thecatontheceiling** [comment]
fixed the issue - had to go to the .png, change one pixel, and then save.

godot compiled it properly after 
wtf lol
