### ISSUE TITLE
Add conversion support to the audio format .oggvorbisstr

### ISSUE THREAD

**Issue by Jazzky** [bruvzg/gdsdecomp#175]
### Describe the problem or limitation you are having

The ogg converter only shows the .oggstr format in the filter.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Could you add the .oggvorbisstr format to the filter to make it easier like you did for exemple with images (.stex and .ctex)?

**Comment by Crystalwarrior** [comment]
Any way to do it manually right now?

**Comment by ZazaZeroff** [comment]
Just filter the file explorer window with "All Files (*)" and you should be able to select your oggvorbisstr file and it should normally convert it with no issues. I opened this enhancement issue just so that things become more obvious and simple.

**Comment by nikitalita** [comment]
this is fixed in the latest release.
