### ISSUE TITLE
Decompiling scripts with strings containing escape sequences

### ISSUE THREAD

**Issue by ArahnaBytes** [bruvzg/gdsdecomp#18]
If script defines strings with special symbols, decompiled script will leave them unescaped. In result strings with new line symbols will ruin script formatting. Attempting recompiling such scripts will generate empty gdc file without any error message.

For example string "\n\nText.\n" will be decompiled like this:
var text = "

Text.
"

**Comment by nikitalita** [comment]
that should have been fixed here? https://github.com/bruvzg/gdsdecomp/commit/665b8e992a48291d9fef8b13f040684bc7b1e804
