### ISSUE TITLE
Can't decompile an exe made in GODOT 4.3.0

### ISSUE THREAD

**Issue by PlasmaticRiver** [bruvzg/gdsdecomp#182]
### System information

Windows 10, GTX 1080 Ti

### Issue description

Program hangs and crashes when attempting to decompile an exe made in GODOT 4.3.0. Does not produce log file.

### Recovery log

N/A

### Minimal reproduction project

https://nachogames.itch.io/thats-not-my-neighbor/

**Comment by nikitalita** [comment]
When the build job is finished here, give the standalone artifacts a try: https://github.com/bruvzg/gdsdecomp/actions/runs/11101629658?pr=183

**Comment by lvplay2** [comment]
> When the build job is finished here, give the standalone artifacts a try: https://github.com/bruvzg/gdsdecomp/actions/runs/11101629658?pr=183

It does not work with the standalone version either.

**Comment by nikitalita** [comment]
I tested this locally myself, this does work; are you loading the PCK file when attempting to decompile? You should only attempt to decompile an EXE if it's an exe with an embedded PCK.

**Comment by PlasmaticRiver** [comment]
> I tested this locally myself, this does work; are you loading the PCK file when attempting to decompile? You should only attempt to decompile an EXE if it's an exe with an embedded PCK.

The exe is embedded with a PCK. An older version of this exe made with GODOT 4.2 decompiles fine with 0.6.2. It just hangs for me, haven't gotten it to work on any PC.

**Comment by nikitalita** [comment]
When the build action finishes here, can you give the standalone artifacts here a shot?
https://github.com/nikitalita/gdsdecomp/actions/runs/11176918108

**Comment by lvplay2** [comment]
> When the build action finishes here, can you give the standalone artifacts here a shot? https://github.com/nikitalita/gdsdecomp/actions/runs/11176918108

Now it works! tysm
