### ISSUE TITLE
Crash when attempting to decompile 4.3 exe

### ISSUE THREAD

**Issue by Borfie** [bruvzg/gdsdecomp#186]
### System information

Windows 11

### Issue description

Using v0.7.0-prerelease.1 , the program immediately hangs when attempting to open the exe of a game compiled in 4.3. Creates no crash log and instantly goes to "Not Responding".

### Recovery log

N/A

**Comment by nikitalita** [comment]
which game?

**Comment by lvplay2** [comment]
> which game?

It doesn't happen with a specific game, it happens with all the games that are made in that version of Godot.

**Comment by nikitalita** [comment]
I tested this locally myself with Wizzerd Quest 1, this does work; are you loading the PCK file when attempting to decompile? You should only attempt to decompile an EXE if it's an exe with an embedded PCK.

**Comment by nikitalita** [comment]
I was testing the macos version; I was indeed able to reproduce on windows. 

When the build action is finished here, can you try the standalone artifacts and see if that works for you? https://github.com/nikitalita/gdsdecomp/actions/runs/11176918108

**Comment by nikitalita** [comment]
I fixed the gdscript failure, but I ran into a out-of-memory error that is causing malloc to segfault; I'm not sure if I've fixed it, please give these artifacts a shot: https://github.com/bruvzg/gdsdecomp/actions/runs/11186117123?pr=191

**Comment by nikitalita** [comment]
Try this: every resource with “smallship” in the name, uncheck those and then try recovery. I have a hunch.

**Comment by nikitalita** [comment]
It's a bug in Godot. The small ship textures are a 1x1 compressed DXT textures that are only 1x1 pixel and are all white; a combination of worse case decompression and bad luck with memory usage can cause Godot to do a misaligned write. Unfortunately, I can't do much about that besides reporting it.

**Comment by nikitalita** [comment]
I implemented a detection for bad textures like these and now we just refuse to export them, along with any other resource that depends on them. This should stop it from crashing during the Wizzerd Quest export. Try the artifact here: https://github.com/bruvzg/gdsdecomp/actions/runs/11197040338

**Comment by nikitalita** [comment]
btw @kondoorsoft-trent , those textures technically break the spec; the minimum size for DXT1 textures is 4x4, and these textures are 1x1. I'm able to get it to consistently crash in the editor when trying to load them on current godot master. You may want to re-import the textures and model.
