### ISSUE TITLE
Compiling a script outputs an empty file, no errors detected

### ISSUE THREAD

**Issue by Ryhon0** [bruvzg/gdsdecomp#187]
### System information

Arch Linux

### Issue description

I want to add mod support to an existing game, I've extracted the pck with godotpcktool since project recovery hanged. I've modified a script and want to compile it but it results in an empty file in the output dir with this log. I've tried using the latest pre-release and latest CI build with 4.3.0 bytecode selected
```
-2024-10-02-10-36-45 [Compile]: compiling Menu.gd
-2024-10-02-10-36-45 [Compile]: No errors detected.
-2024-10-02-10-36-45 [Compile]: The operation completed successfully!
ERROR: Method/function failed. Returning: Vector<uint8_t>()
   at: compile_code_string (modules/gdsdecomp/bytecode/bytecode_base.cpp:1476)
```

### Recovery log

N/A

### Minimal reproduction project

The script I want to compile:
[Menu.gd.txt](https://github.com/user-attachments/files/17226583/Menu.gd.txt)

**Comment by nikitalita** [comment]
When the build action is done, can you please try the standalone artifacts here?
https://github.com/bruvzg/gdsdecomp/actions/runs/11178111731?pr=190

**Comment by Ryhon0** [comment]
Yup, works now
