### ISSUE TITLE
Errors when export EXE file

### ISSUE THREAD

**Issue by SAn4Es-TV** [bruvzg/gdsdecomp#188]
### System information

Windows 11

### Issue description

Using v0.7.0-prerelease.1, the program immediately freezes when trying to open the game exe. Does not create a crash log and immediately goes into the "Not responding" state. If you use the decompiler in the console, errors appear in the output and the log file is saved in the game folder

### Recovery log

If use decompiller in console, it return log file 
[gdre_export.log](https://github.com/user-attachments/files/17255030/gdre_export.log)

**Comment by nikitalita** [comment]
Load the PCK file, not the EXE file.

**Comment by nikitalita** [comment]
Just curious, where are you guys getting your instructions from?

**Comment by SAn4Es-TV** [comment]
There is no PKG file in the game folder
![image](https://github.com/user-attachments/assets/df157efb-7974-43c5-a9a6-783e53b7fec4)

**Comment by nikitalita** [comment]
Hmm, I must have grabbed the wrong one. Where did you download this?

**Comment by SAn4Es-TV** [comment]
The name of the game is Beat Banger. You can download it [from Steam](https://store.steampowered.com/app/1813430/Beat_Banger/).

**Comment by nikitalita** [comment]
Did you really think that I'd buy and download a furry porn game?

Well, you were correct.

It works fine on the latest version, please give that a shot.

**Comment by SAn4Es-TV** [comment]
Thanks! Everything works great.
