### ISSUE TITLE
Recompiled Decomped Project can't be read

### ISSUE THREAD

**Issue by wfzyx** [bruvzg/gdsdecomp#198]
### System information

Linux/Fedora

### Issue description

I have a .exe generated by godot 3.5.6 which is a mod from an already decompiled source made by gdsdecomp that the tool doesn't know how to decomp again;

### Steps to reproduce

https://github.com/bruvzg/gdsdecomp/blob/ce4d4cf1186271cd9b18b5140f870f062131aefb/utility/gdre_packed_source.cpp#L336

Seems like its failing to parse utf8?  I'm not super C++ savy; will try cloning the project and see whats going on

### Recovery log

[gdre_export.log](https://github.com/user-attachments/files/17405513/gdre_export.log)

### Minimal reproduction project

wfzyx on discord for a sample of the file that causes the error

**Comment by nikitalita** [comment]
There appears to be a file prefixed with "gdre_" in the .exe.  Did you accidentally include the gdre_recovery.log in the pck?

**Comment by wfzyx** [comment]
[gdre_export.log](https://github.com/user-attachments/files/17438806/gdre_export.log)

on this build there is a regression - https://github.com/bruvzg/gdsdecomp/pull/199 - there is some audio files that got lost during the decomp; but it indeed fixes the crash it had before

**Comment by wfzyx** [comment]
[0.7.3 log](https://github.com/user-attachments/files/17441757/gdre_export.log)
[last commit log](https://github.com/user-attachments/files/17441790/gdre_export.log)
