### ISSUE TITLE
error while rebuilding Godot

### ISSUE THREAD

**Issue by Naeta2** [bruvzg/gdsdecomp#2]
hey, thank you for this program. I am trying to rebuild Godot with your module, but i systematically end up getting this error : 

![image](https://user-images.githubusercontent.com/46900232/51487255-22aabb80-1da3-11e9-85d6-4ae7f82f3b6d.png)

the translation could roughly be : 
"the expression has not been evaluated in constant
failure is due to reading an obsolete variable
see the use of 'bufsize' "

it points to these four identical lines in the code : 

uint8_t buf[bufsize]; 

do you have any idea on how to fix that ? thanks a lot.

**Comment by bruvzg** [comment]
Looks like MSVC wants to have size of the array as constant, this should be fixed by 5da89a49718e45c41ce60cab3dcccec7f2c05323.

**Comment by Naeta2** [comment]
thank you for the quick answer, i'll try this right away

**Comment by Naeta2** [comment]
ok the compiling worked now ! thank you very much
