### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by zanderlewis** [bruvzg/gdsdecomp#201]
### Describe the problem or limitation you are having

You currently cannot decompile MacOS binaries, only EXE files.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add support for decompiling MacOS binaries

**Comment by bruvzg** [comment]
macOS binaries can't have embedded PCK, there's nothing to decompile.

**Comment by nikitalita** [comment]
drag and drop the .app onto the app window.
