### ISSUE TITLE
GDRE freezes when I select to decompile only specific folders.

### ISSUE THREAD

**Issue by thecatontheceiling** [bruvzg/gdsdecomp#205]
### System information

Windows 10

### Issue description

Wanted to read the GDScript code for a game, opened GDRE latest master branch build, selected only the "scripts" and another folder, pressed export and after exporting the scripts it froze and I had to kill it from task manager.
If I select to export all files it works fine, but it takes a lot longer.

### Steps to reproduce
1. Get Buckshot Roulette
2. Open GDRE, select the BR EXE.
3. Select only the "scripts" and the "multiplayer" folder, continue.
4. GDRE freezes and windows says "not responding". Still uses CPU according to task manager but very little memory usage and no disk usage.
![image](https://github.com/user-attachments/assets/5f73047c-266d-4470-8d66-27a59923ed6e)

### Recovery log
[gdre_export.log](https://github.com/user-attachments/files/17568959/gdre_export.log)

### Minimal reproduction project

I used https://store.steampowered.com/app/2835570/Buckshot_Roulette/ but I am not sure if any other games are affected or not.

**Comment by thecatontheceiling** [comment]
Fixed by switching from "Full Recovery" to "Extract Only"

**Comment by nikitalita** [comment]
I think I have fixed this; can you give the standalone artifacts here a try? https://github.com/bruvzg/gdsdecomp/actions/runs/11605124703?pr=208

**Comment by thecatontheceiling** [comment]
Yup that build doesn't have the problem
