### ISSUE TITLE
0.8 crashes while exporting resources

### ISSUE THREAD

**Issue by Mathieu015** [bruvzg/gdsdecomp#206]
### System information

Windows 11, NVIDIA GeForce RTX 4080 Laptop GPU

### Issue description

GDRE 0.8 prelease 1 crashes while exporting the resources.

### Recovery log

N/A 

### Minimal reproduction project

Have the issue with The Case of the Golden Idol (gog version with all DLC), Dome Keeper and another game. Two games (Buckshot Roulette (itch version) and an other) doesn't have that issue.

**Comment by nikitalita** [comment]
Can you try running recovery for those games in [CLI mode](https://github.com/bruvzg/gdsdecomp?tab=readme-ov-file#command-line) and copy/paste the terminal output?

**Comment by Mathieu015** [comment]
Tested it with Golden Idol and Dome Keeper. Here's their logs:
-Golden Idol: 
[gdre_export.log](https://github.com/user-attachments/files/17581256/gdre_export.log)
-Dome Keeper: 
[gdre_export.log](https://github.com/user-attachments/files/17581258/gdre_export.log)
It shows me that and then nothing. Forced to stop after waiting for 5-10 minutes. There's no way to tell if it's still working or if it crashed or just stopped. Would be better if it gives more infos.

**Comment by Mathieu015** [comment]
Just redone with task manager open. And I see (I recorded it) that the program just close itself. No error messages.

**Comment by Mathieu015** [comment]
No change. Still close itself. GUI and CLI tested.

**Comment by nikitalita** [comment]
Ok, I got Dome Keeper and I tracked down the crash, try this one: https://github.com/bruvzg/gdsdecomp/actions/runs/11623418896?pr=209

**Comment by Mathieu015** [comment]
Ok. Seems to be working. I can now compare the folders and I see some differences with the jpg and jpeg files.
