### ISSUE TITLE
0.8 pre 1 - Scenes are broken

### ISSUE THREAD

**Issue by Mathieu015** [bruvzg/gdsdecomp#207]
### System information

Windows 11, NVIDIA GeForce RTX 4080 Laptop GPU

### Issue description

Open recovered project into Godot 4 failed to load some scenes.
Show that error in the Godot Editor lot of time: "Parse Error: Saved with newer format version"

### Steps to reproduce

Recover project
Open in Godot 4.1.4 

### Recovery log

[gdre_export.log](https://github.com/user-attachments/files/17580323/gdre_export.log)

### Minimal reproduction project

Tested it with Buckshot Roulette (itch version).

**Comment by nikitalita** [comment]
Thanks for testing! For some reason, the log didn't upload correctly; can you upload it again?

**Comment by Mathieu015** [comment]
[gdre_export.log](https://github.com/user-attachments/files/17580723/gdre_export.log)

**Comment by nikitalita** [comment]
thanks! I think this PR fixes it; when the build action is done, can you give the standalone artifacts here a try? https://github.com/bruvzg/gdsdecomp/actions/runs/11604639490?pr=208

**Comment by Mathieu015** [comment]
Ok. It works.
