### ISSUE TITLE
new release version ? 

### ISSUE THREAD

**Issue by maxcodeir** [bruvzg/gdsdecomp#21]
hi,
I downloaded _gdretools_linux64_0.0.6.zip_ , i think it is old version ,but it's work :+1: 
can you update new release version?  because i can't compile godot source on linux ...
thank you.

**Comment by nikitalita** [comment]
Need to tag a new release version because it is relatively stable now (despite being out of sync with `master`) and the artifacts from the auto builds keep expiring.
