### ISSUE TITLE
0.7.3 -> 0.8 pre 3 - jpeg files are differents

### ISSUE THREAD

**Issue by Mathieu015** [bruvzg/gdsdecomp#210]
### System information

Windows 11, NVIDIA GeForce RTX 4080 Laptop GPU

### Issue description

I see, while comparing two recovery folders made by 0.7.3 and 0.8 pre 3, that the jpeg (jpeg, jpg, etc.) files are "differents". Different sizes and on one of them, I see a different color value on a pixel.

### Steps to reproduce

-Recover project (both 0.7.3 and latest 0.8 pre 3 dev)
-Compare the two folders (I'm using WinMerge)

### Recovery log

N/A

### Minimal reproduction project

Tested with "Case of The Golden Idol" (gog with all DLC's) I see different pixels with color values in a jpg file.
<img width="869" alt="2024-11-01 002917" src="https://github.com/user-attachments/assets/7992e9bd-1575-414c-8887-31fb6867d485">
[tower-jpg.zip](https://github.com/user-attachments/files/17596055/tower-jpg.zip)

**Comment by nikitalita** [comment]
Yeah, we switched jpeg encoders to fix the previous bug; we moved from an external one to the internal Godot one, and given that jpeg is always a lossy encoding (at least, with the schemes that Godot supports decoding from), the results might be slightly different.

**Comment by nikitalita** [comment]
After further testing, the differences are incredibly slight, if they exist at all; I'm ok with this.
