### ISSUE TITLE
0.8: missing datas in the logs

### ISSUE THREAD

**Issue by Mathieu015** [bruvzg/gdsdecomp#211]
### System information

Windows 11, NVIDIA GeForce RTX 4080 Laptop GPU

### Issue description

In 0.8, there's no mentions about some formats (svg for example) being converted to a lossy format except for jpg files. Just realize that "Non-importable conversions" are always gives 0 ("Decompiled scripts" too for some). And probably more infos are missing or incorrect.

### Recovery log

Dome keeper: 
0.7.3 
[gdre_export.log](https://github.com/user-attachments/files/17596243/gdre_export.log)
0.8
[gdre_export.log](https://github.com/user-attachments/files/17596247/gdre_export.log)
Buckshot Roulette:
0.7.3
[gdre_export.log](https://github.com/user-attachments/files/17596278/gdre_export.log)
0.8
[gdre_export.log](https://github.com/user-attachments/files/17596288/gdre_export.log)
Case of The Golden Idol:
0.7.3
[gdre_export.log](https://github.com/user-attachments/files/17596297/gdre_export.log)
0.8
[gdre_export.log](https://github.com/user-attachments/files/17596300/gdre_export.log)

### Minimal reproduction project

Used 0.8 pre 3 dev.

**Comment by nikitalita** [comment]
Try the latest pre-release, I think i've fixed these: https://github.com/bruvzg/gdsdecomp/releases/tag/v0.8.0-prerelease.3

**Comment by Mathieu015** [comment]
Case of the Golden Idol: No change. Still no mention about svg data converted: 
[gdre_export.log](https://github.com/user-attachments/files/17609406/gdre_export.log)
Buckshot Roulette: Still says 0 decompiled scripts: 
[gdre_export.log](https://github.com/user-attachments/files/17609408/gdre_export.log)
Dome Keeper:  Same as Buckshot Roulette:
[gdre_export.log](https://github.com/user-attachments/files/17609410/gdre_export.log)

**Comment by nikitalita** [comment]
Buckshot Roulette is supposed to have 0 decompiled scripts, as it has no compiled scripts in the PCK. If we reported we decompiled those scripts in previous versions, that was a bug.

However, It is so odd that the svg files aren't showing up for you; I specifically tested Buckshot Roulette and Dome Keeper for the svg files and they did show up in the log files for me. What OS are you using?
