### ISSUE TITLE
0.8 pre 4 - Error: failed to detect GDScript revision

### ISSUE THREAD

**Issue by Mathieu015** [bruvzg/gdsdecomp#216]
### System information

Windows 11, NVIDIA GeForce RTX 4080 Laptop GPU

### Issue description

Importing any game show some errors related to detecting GDScript revision. Sometimes, it gives an error and a warning (probably 3.x only) and for others, only the warning (probably 4.x).

### Recovery log

N/A

### Minimal reproduction project

<img width="475" alt="2024-11-06 072529" src="https://github.com/user-attachments/assets/57453cd4-6396-4b8c-ad49-9506749d0eff">
<img width="474" alt="2024-11-06 072252" src="https://github.com/user-attachments/assets/3ca9c6a2-6a06-47f6-b5b7-d3b66cc6832b">
<img width="477" alt="2024-11-06 072110" src="https://github.com/user-attachments/assets/49dd89d9-db17-40b0-855e-63b8448a6327">

**Comment by nikitalita** [comment]
which games?

**Comment by Mathieu015** [comment]
Case of the Golden Idol, Dome Keeper, Buckshot Roulette and another one that I can't name here and that need to use an encryption key (the one that tell me to report that to github). Windows GUI.

**Comment by Mathieu015** [comment]
Sorry to ask that, but I don't understand how I should do this.

**Comment by nikitalita** [comment]
That's ok; on Discord, click the Discord icon at the top on the sidebar, click "Friends", go to the "Add Friend" tab, and type "nikita_lita" in the bar, then click send friend request
<img width="929" alt="image" src="https://github.com/user-attachments/assets/fee3f3d9-0df4-40c7-8144-fda136f28e47">
