### ISSUE TITLE
Crashes When Decompiling Psychopomp Gold, Seems Unrelated To Previous Issue

### ISSUE THREAD

**Issue by FragileDeviations** [bruvzg/gdsdecomp#218]
### System information

Windows 11, NVIDIA RTX 3060 12 GB

### Issue description

Crashes halfway through trying to decompile Psychopomp Gold.
Seems unrelated to the texture issue now, though. The log doesn't show much helpful, at least from what I can see.
I know there's another issue related to this that's now closed, but the issue persists and it looks to be different.

### Steps to reproduce

1. Drag Psychopomp Gold's executable into the app
2. Watch the crash

### Recovery log

[gdre_export.log](https://github.com/user-attachments/files/17652449/gdre_export.log)

### Minimal reproduction project

https://store.steampowered.com/app/3243190/Psychopomp_GOLD/

**Comment by Alex-gnzl** [comment]
I can't replicate this on Linux and win32/wine anymore as of 8302d71036ca81ee17f1cebbfbc2a55126d7d942.
Are you running the latest build from Actions (not release)?

**Comment by nikitalita** [comment]
I've reproduced. It's pretty nasty and it looks like it's a bug in GLTFDocument. In the meantime, try excluding "res://.godot/imported/Shader.blend-<bunchofgarbage>" from the export.

**Comment by FragileDeviations** [comment]
Excluding that fixed it for me.

**Comment by xChillax** [comment]
I used "v0.8.0-prerelease.6" and it didn't crash when decompiling it unlike before.

**Comment by nikitalita** [comment]
Just curious, @FragileDeviations do you still get a crash on that resource with the latest release? https://github.com/bruvzg/gdsdecomp/releases/latest

**Comment by FragileDeviations** [comment]
Latest release seems to work!
