### ISSUE TITLE
Program impossible to use on smaller resolution monitors

### ISSUE THREAD

**Issue by art0007i** [bruvzg/gdsdecomp#22]
When trying to use the program on a smaller resolution monitors the popups are too large to work with, and they are also unresizeable, resizing cursor shows up but does not do anything.
Here is an image that shows this issue
![image](https://user-images.githubusercontent.com/19620451/120783237-1b774900-c52b-11eb-99ae-a9711b39fa93.png)
The extract button is completely unreachable

**Comment by bruvzg** [comment]
Should be fixed in bfbb9e3 (and [v0.0.7](https://github.com/bruvzg/gdsdecomp/releases/tag/v0.0.7) release).
