### ISSUE TITLE
Prerelease has issues decompiling YomiHustle

### ISSUE THREAD

**Issue by TriMay** [bruvzg/gdsdecomp#223]
### System information

Windows 10

### Issue description

Issues:

![image](https://github.com/user-attachments/assets/d035e718-63eb-497f-b02e-418507d9bac6)

[with 0 8 0 project.godot](https://github.com/user-attachments/files/17808183/incorrect.project.godot.txt)
[with 0 6 2 project.godot.txt](https://github.com/user-attachments/files/17808190/correct.project.godot.txt)

Main scene is set to the incorrect scene (gdre_main.tscn instead of Main.tscn)
Project settings are not correct (resolution is incorrect as well as main scene)

### Steps to reproduce

Decompile Your Only Move Is HUSTLE with 0.8.0

### Recovery log

[gdre_export.log](https://github.com/user-attachments/files/17808150/gdre_export.log)

**Comment by nikitalita** [comment]
This is fixed on the latest master, I will tag a new release sometime today.

**Comment by Mitaka712** [comment]
when is it coming out

**Comment by nikitalita** [comment]
right now: https://github.com/bruvzg/gdsdecomp/releases/latest
