### ISSUE TITLE
[RELEASE v0.0.7] Scripts containing "as type" missing space before as

### ISSUE THREAD

**Issue by Jimmio92** [bruvzg/gdsdecomp#23]
Decompiling scripts from a project I thought I lost forever (bruvzg I love you), I noticed anywhere I typed "x as float", it would become "xas float". Minor issue :)

**Comment by nikitalita** [comment]
I thought I had fixed that... Can you post the project?

**Comment by Jimmio92** [comment]
Oh I'm terribly sorry, I should have included this was in the newest of the releases available for download, not necessarily master branch. I should have made that clear initially and I assume this means it's fixed and I shouldn't have wasted y'alls time as it just needs rebuilt and reuploaded. Should I keep this open and just correct the title or close it since it's technically fixed? Or should it be considered a bug since there's no release available fixing this?

Thanks,
Jim

**Comment by nikitalita** [comment]
I think we should probably release a version on the master branch; there's no reason to not do so for the standalone.

**Comment by sairam4123** [comment]
I have the same problem, instead of missing space for "as type", I have a missing space before all "class Name extends Base: "

**Comment by nikitalita** [comment]
Release has happened
