### ISSUE TITLE
Unable to Compile Godot 

### ISSUE THREAD

**Issue by FooF-555** [bruvzg/gdsdecomp#29]
I am unable to compile Godot with gdsdecomp because there is no module called stb_vorbis, the error states:
modules\gdsdecomp\editor\gdre_editor.cpp(20): fatal error C1083: Cannot open include file: 'modules/stb_vorbis/audio_stream_ogg_vorbis.h': No such file or directory
scons: *** [modules\gdsdecomp\editor\gdre_editor.windows.tools.64.obj] Error 2
scons: building terminated because of errors.

**Comment by nikitalita** [comment]
oops, looks like they switched to use libvorbis instead of stb_vorbis: https://github.com/godotengine/godot/pull/52406

Try checking out https://github.com/godotengine/godot/commit/fd0a2b6cde85d737dbe9155b84c363732b8274e6 and see if that works.
