### ISSUE TITLE
scripts from a godot 2.1.3 project

### ISSUE THREAD

**Issue by Naeta2** [bruvzg/gdsdecomp#3]
helloo, it's me again

i'm so sorry to bother you with these issues, i'd like to be able to resolve them myself.

i have one or two quick questions. i'm trying to get back old scripts from a game made with godot 2.1.3. 

you say in the readme that i would need to use the module with godot 2.1.3 engine to decompile the .gdc scripts into .gd, but the module is only compatible with 3.1 ?
I tried to decompile those files with a 3.1 build but whenever i do this godot freezes and become unresponsive (it still use more and more memory in the task manager so i first assumed it was working on the key encryption and tried to get the key back by disassembling the .exe but i could not find it)
I also desperately tried to add the module to a 2.1.3 build but it didn't work, i got an issue with scons

Do you plan to make the module compatible with older builds of the engine in the future ?
or do you think it's related to the encryption key as i first thought ? in this case do you have any idea on how to get it from the exe since i can't seem to be able to find it ? i'm really not very good with the disassemblers and everything

thanks a lot, i'm really impressed by your work !

**Comment by bruvzg** [comment]
Added some support for older byte-code in 28861f535968d2b94b7ad2aefdffbcf973311c0f.

I have tested only 3.1 / 3.0 versions, but 2.x script should work too.

**Comment by girng** [comment]
damn, @bruvzg is on it. wow 🚀

**Comment by Naeta2** [comment]
you are a legend my friend !

**Comment by bruvzg** [comment]
Closing this, all GDScript versions should be supported by now.
