### ISSUE TITLE
Stex to image [Write Error?]

### ISSUE THREAD

**Issue by KevanAwesome** [bruvzg/gdsdecomp#31]
![image](https://user-images.githubusercontent.com/23181883/136223615-218b2185-ee59-4750-aa24-66bf33803259.png)
This keeps happening and I don't know what is causing it.

**Comment by Annaphorra** [comment]
I have the same issue, is this because I didn't compile into godot?

**Comment by nikitalita** [comment]
There needs to be a new release version of the binary. in the meantime, use this one: https://github.com/bruvzg/gdsdecomp/actions/runs/1672274116#artifacts

**Comment by nikitalita** [comment]
Release has happened
