### ISSUE TITLE
Compiling errors caused by absense of files inside a `core` folder that does not exist

### ISSUE THREAD

**Issue by ultima-gay** [bruvzg/gdsdecomp#34]
I have been attempting to compile gdsdecomp as described in the readme, by placing `gdsdecomp` within `modules` (using Godot 3.3.4, the most recent release) and then compiling godot as normal, but I receive this error each time:

```register_types.cpp
modules\gdsdecomp\register_types.cpp(6): fatal error C1083: Cannot open include file: 'core/object/class_db.h': No such file or directory
scons: *** [modules\gdsdecomp\register_types.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

I do not understand this error, but to my understanding no `core` folder exists in gdsdecomp, and the `class_b.h` file in godot 3.3.4 is located within `core` itself, and no `core/object` folder seems to exist. Whatever is occuring, it seems to be caused by files that are being included in the files but do not actually exist as the folder they would be in is absent, and the corresponding files from godot are in completely different folders within `core`

**Comment by bruvzg** [comment]
You are building the wrong version of the module, `master` branch of the module is for Godot 4.0. Use branch `3.x` for Godot 3.x.
