### ISSUE TITLE
Support usage outside the Godot engine, as a standalone program

### ISSUE THREAD

**Issue by CypElf** [bruvzg/gdsdecomp#46]
Hello, I would suggest to create another version of the project besides the Godot module.
It would be way easier to use, as it's not the easiest thing to have to recompile the Godot engine with this module.
With the module already working great, this would be awesome to just be able to download and run a standalone version to use it directly.

**Comment by nikitalita** [comment]
There is a standalone program, it's not in the releases yet but it can be found in the build artifacts: https://github.com/bruvzg/gdsdecomp/actions/runs/1672274116#artifacts

**Comment by nikitalita** [comment]
Remind me again this weekend, I'll tag a release along with updated documentation

**Comment by CypElf** [comment]
Thanks 👍

**Comment by CypElf** [comment]
Still waiting for the release 🙏

**Comment by nikitalita** [comment]
@CypElf I want to put the Full project export into the gui before release, but I don't want to do it.

So, please do it for me.

Thanks,
Your Pal,
Nikita

**Comment by CypElf** [comment]
I'm not sure what you're meaning here

**Comment by sairam4123** [comment]
> @CypElf I want to put the Full project export into the gui before release, but I don't want to do it.
> 
> So, please do it for me.
> 
> Thanks,
> Your Pal,
> Nikita

Guess I'll do it.

**Comment by CypElf** [comment]
Also, could you update the installation section of the README to say that a standalone version is available in the releases?

**Comment by Kein** [comment]
Can I get some thing cleared up from the README?
A quote:

> To perform full project recovery from the command line:
> gdre_tools --extract game.pck --output-dir game-extract/
> Use the same Godot tools version that the original game was compiled in to edit the project. In order to detect this, see [To detect Godot version](https://github.com/bruvzg/gdsdecomp#to-detect-godot-version)

Do I understand correctly that the project recovery dump only available in as-a-module version? Because outputted pack has nothing in common with Godot 3.x project structure and type. The game in question using Godot 3.4.4

**Comment by CypElf** [comment]
up

**Comment by nikitalita** [comment]
New release is up: https://github.com/bruvzg/gdsdecomp/releases/tag/v0.0.8

I wanted to put full project recovery in the GUI to head off support requests, but I see that it's just confusing people now, so I decided to release it without doing that yet. 

@Kein Please use the new standalone release, that should solve your problem.

**Comment by Kein** [comment]
>  Please use the new standalone release, that should solve your problem.

it does not hence why I ask the question - how can I compile it as a module for 3.4.4?
Simple extraction of pack isnt "full project restoration" and I'm looking exactly for the latter as readme states. Project file for example not parsed, it is unuseable binary

**Comment by CypElf** [comment]
> Also, could you update the installation section of the README to say that a standalone version is available in the releases?

Opening a new issue about that to keep it separated from this one.

**Comment by nikitalita** [comment]
> > Please use the new standalone release, that should solve your problem.
> 
> it does not hence why I ask the question - how can I compile it as a module for 3.4.4? Simple extraction of pack isnt "full project restoration" and I'm looking exactly for the latter as readme states. Project file for example not parsed, it is unuseable binary

You can’t. 3.x branch is deprecated.

**Comment by Kein** [comment]
Okay, may be I'm missing something here so please do fill me in: what is the grand idea deprecating actively used LTS engine version? May be I'm misunderstanding main point of project - isnt it to help decompile, unpack and mod games? Majority of Godot games I've encountered use 3.x, because it is LTS, as I said, so what is the logical, pragmatical reason to so quickly and hastily deprecate it?

**Comment by CypElf** [comment]
This isn't the purpose of this issue, please open another one for this

**Comment by nikitalita** [comment]
The `master` version decompiles 2.x-4.x projects, read the Readme.
