### ISSUE TITLE
GDCs not converted when using CLI project export on windows

### ISSUE THREAD

**Issue by The-ThirtyFour** [bruvzg/gdsdecomp#48]
title.
I don't know if this is a windows problem or gdsdecomp's
None gdc where converted to gd, and they aren't encrypted

**Comment by The-ThirtyFour** [comment]
it was a godot 3.4 game
the export command returned that is an unknown version
so, as far i can tell, it is unimplemented
i've managed to edit the standalone to recognize it somehow, and it worked (maybe there's some error, but i didn't found yet)

**Comment by nikitalita** [comment]
> it was a godot 3.4 game the export command returned that is an unknown version so, as far i can tell, it is unimplemented i've managed to edit the standalone to recognize it somehow, and it worked (maybe there's some error, but i didn't found yet)

wait, what? Can you PR your changes?

**Comment by The-ThirtyFour** [comment]
it was a simple edit
just copied
```
elif version.begins_with("3.3"):
decomp = GDScriptDecomp_5565f55.new()
```
and changed to 3.4
i wasn't expecting it to work
