### ISSUE TITLE
Illegal Construction Variable

### ISSUE THREAD

**Issue by JohnTobey** [bruvzg/gdsdecomp#50]
Hello
When I try to recompile Godot in version 3.4.2 I get the error 
`scons: *** Illegal construction variable `module_gdsdecomp-3.x_enabled'
File "/home/john/Documents/Godot Decompile/godot-3.4.2-stable/SConstruct", line 288, in <module>`

I can compile Godot without this fine, and I used gdsdecomp-3.x as well

**Comment by nikitalita** [comment]
Don't compile this with the 3.x branch, compile against master instead. This supports full project recovery for Godot 2.x - 4.x

**Comment by nikitalita** [comment]
Or just use the artifacts here: https://github.com/bruvzg/gdsdecomp/actions/runs/2283325472#artifacts

**Comment by JohnTobey** [comment]
when I compile from master (The one i get by git clone https://github.com/bruvzg/gdsdecomp ) I get the error 
`modules/gdsdecomp/register_types.cpp:6:10: fatal error: core/object/class_db.h: No such file or directory
    6 | #include "core/object/class_db.h"
      |   `

I thought I had to pull from the 3x branch because this error is the same as 
https://github.com/bruvzg/gdsdecomp/issues/13

also, if artifacts is more simple , how can I use them instead?

**Comment by JohnTobey** [comment]
I found out the solution. I pulled from the 3.x branch and the 3.x branch as well and this fixed the solution. the main branch will not work for 3x because some files were moved into their own folder in godot 4.
