### ISSUE TITLE
MacOS Could Not Initialize Vulkan On Godot 4.0 Beta Build

### ISSUE THREAD

**Issue by Blakiemon** [bruvzg/gdsdecomp#51]
I get the error in a prompt 

`Your video card driver does not support any of the supported Vulkan or OpenGL versions.`

when running this newest build https://github.com/bruvzg/gdsdecomp/actions/runs/2283325472

In the terminal it outputs 

```
barens-MacBook-Pro:~ blake$ /Users/blake/Downloads/GDRE\ Tools.app/Contents/MacOS/GDRE\ Tools --verbose
arguments
0: /Users/blake/Downloads/GDRE Tools.app/Contents/MacOS/GDRE Tools
1: --verbose
Current path: /Users/blake
TextServer: Added interface "ICU / HarfBuzz / Graphite"
TextServer: Added interface "Fallback"
Godot Engine v4.0.dev.custom_build.489f11ee0 - https://godotengine.org
ERROR: Could not initialize Vulkan
   at: DisplayServerOSX (platform/osx/display_server_osx.mm:3789)
```

I am running MacOS 10.14.6 on a Macbook Pro Mid 2015 model.

**Comment by nikitalita** [comment]
Hmmm, that is peculiar. Have you tried any of the recent Godot 4.x master builds to see if those run?

**Comment by nikitalita** [comment]
I.e. try these ones and see if they run: https://github.com/godotengine/godot/actions/runs/2367296239#artifacts

**Comment by bruvzg** [comment]
CI artifacts are built with dynamically linked MoltenVK, and require Vulkan SDK to be installed to run.

**Comment by Blakiemon** [comment]
> CI artifacts are built with dynamically linked MoltenVK, and require Vulkan SDK to be installed to run.
> 
> https://vulkan.lunarg.com/sdk/home#mac

Hi there, I installed the newest Vulkan to /Users/blake/VulkanSDK/1.3.211.0 (and yes I restarted my computer) however I'm still getting the same error message. I'm using the standalone version if that helps `GDRE_tools-standalone-osx`

**Comment by Blakiemon** [comment]
> I.e. try these ones and see if they run: https://github.com/godotengine/godot/actions/runs/2367296239#artifacts

I tried running it, I got some errors in the terminal and after 10 seconds a window pops up
![image](https://user-images.githubusercontent.com/47361570/169846900-02435e33-92be-4b68-bb60-7749908a1df8.png)

Here is my terminal output if this helps
[Godot 4.0 Output.txt](https://github.com/bruvzg/gdsdecomp/files/8755653/Godot.4.0.Output.txt)

**Comment by nikitalita** [comment]
> CI artifacts are built with dynamically linked MoltenVK, and require Vulkan SDK to be installed to run.
> 
> https://vulkan.lunarg.com/sdk/home#mac

Is there a way to statically link them so that installing the SDK is not required?

**Comment by bruvzg** [comment]
> Is there a way to statically link them so that installing the SDK is not required?

Yes, but this requires SDK installation on the CI vm. Static linking is done with the `use_volk=no VULKAN_SDK_PATH=/path/to/VulkanSDK/1.3.204.1/` build flags.

**Comment by nikitalita** [comment]
> > I.e. try these ones and see if they run: https://github.com/godotengine/godot/actions/runs/2367296239#artifacts
> 
> I tried running it, I got some errors in the terminal and after 10 seconds a window pops up ![image](https://user-images.githubusercontent.com/47361570/169846900-02435e33-92be-4b68-bb60-7749908a1df8.png)
> 
> Here is my terminal output if this helps [Godot 4.0 Output.txt](https://github.com/bruvzg/gdsdecomp/files/8755653/Godot.4.0.Output.txt)

I confirmed this on a mac; it looks like there may be an issue with using `volk` with vulkan 1.3 SDKs? I'm going to try statically compiling against the Vulkan SDK and see if that works

**Comment by nikitalita** [comment]
@Blakiemon Which mac model are you using?

**Comment by nikitalita** [comment]
@Blakiemon please give the artifacts from this run a shot: https://github.com/bruvzg/gdsdecomp/actions/runs/2399523878

**Comment by Blakiemon** [comment]
> @Blakiemon Which mac model are you using?

MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by Blakiemon** [comment]
> @Blakiemon please give the artifacts from this run a shot: https://github.com/bruvzg/gdsdecomp/actions/runs/2399523878

I just tried out `[GDRE_tools-standalone-osx]`

And it works! Thank you! Looks like using this newer version didn't solve my problem of GDRE not being able to convert a project.binary file to text. Time to open a new issue

Also, I did notice a few errors in the terminal and it took about 10 seconds for the program to launch, so here's my output just in case:

```
0: /Users/blake/Downloads/Godot RE Tools.app/Contents/MacOS/Godot RE Tools
Current path: /Users/blake
Godot Engine v4.0.alpha.custom_build.ff75a4922 - https://godotengine.org
Vulkan API 1.1.204 - Using Vulkan Device #0: Intel - Intel Iris Pro Graphics
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
ERROR:  - Message Id Number: 0 | Message Id Name: 
	VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140267819588096
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:159)
ERROR: vkCreateGraphicsPipelines failed with error -3 for shader 'ClusterRenderShaderRD:0'.
   at: render_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6614)
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
ERROR:  - Message Id Number: 0 | Message Id Name: 
	VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140267819588096
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:159)
ERROR: vkCreateGraphicsPipelines failed with error -3 for shader 'ClusterRenderShaderRD:0'.
   at: render_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6614)
```
