### ISSUE TITLE
Cannot convert project.binary back to text

### ISSUE THREAD

**Issue by Blakiemon** [bruvzg/gdsdecomp#55]
Hi there, after unpacking a .pck I want to convert the project.binary back to text, however when doing so on the latest MacOS release I get this error in the output:
![screenshot](https://user-images.githubusercontent.com/47361570/170890386-2eca8333-764f-439b-bd30-cbaa2702f89c.png)

And when running in terminal this is my output:
```
ERROR: Unable to recognize  '/Users/blake/Downloads/May Rocket Export/project.binary'.
   at: open (modules/gdsdecomp/utility/resource_loader_compat.cpp:224)
ERROR: Cannot open resource '/Users/blake/Downloads/May Rocket Export/project.binary'.
   at: convert_bin_to_txt (modules/gdsdecomp/utility/resource_loader_compat.cpp:24)
```

I am running macOS 10.14.6 on a MacBook Pro (Retina, 15-inch, Mid 2015)

The version I am running of GDRE is GDRE_tools-standalone-osx from this build: https://github.com/bruvzg/gdsdecomp/actions/runs/2399523878

**Comment by nikitalita** [comment]
you can't use the "convert binary to text" option in the menu to convert the project.binary. Right now, that only happens when you either do a PCK extraction in the GUI or a full project recovery from the CLI

**Comment by Blakiemon** [comment]
> you can't use the "convert binary to text" option in the menu to convert the project.binary. Right now, that only happens when you either do a PCK extraction in the GUI or a full project recovery from the CLI

How would I do a full project recovery from the CLI? (The arguments in particular)

**Comment by nikitalita** [comment]
https://github.com/bruvzg/gdsdecomp/pull/52
