### ISSUE TITLE
How do i compile .GD script files back to .GDC format?

### ISSUE THREAD

**Issue by Karri966** [bruvzg/gdsdecomp#56]
As the title says im looking for a solution to this since the gdre_tools.exe has the "Compile .GD script files..." button but its grayed out.

**Comment by nikitalita** [comment]
Try the new standalone release: https://github.com/bruvzg/gdsdecomp/releases/tag/v0.0.8

**Comment by Kein** [comment]
`Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).`

**Comment by nikitalita** [comment]
what version are you using?

**Comment by Kein** [comment]
Oh nevermind, I renamed executable but it looks like it searches for pack with the same name as binary so it failed.

**Comment by nikitalita** [comment]
yeah, that's a Godot limitation. Does GDC compiling work now?

**Comment by CoderGuy-0** [comment]
I still can't compile the GD files back to GDC format. Here's a screenshot showing the option is still grayed out after extracting the .pck file and decrypting the gdc files: https://prnt.sc/NXTfItnM9HQg

**Comment by nikitalita** [comment]
@bruvzg ?

**Comment by Kein** [comment]
Same

**Comment by bruvzg** [comment]
There's no custom compilers for each of the versions implemented. So the easiest way to compile it back is taking an appropriate version of the engine (https://downloads.tuxfamily.org/godotengine/) adding script to the empty project, exporting it as zip and extract compiled script.

**Comment by nikitalita** [comment]
This is now implemented.
