### ISSUE TITLE
Is it possible to do full project recovery on an apk file?

### ISSUE THREAD

**Issue by PistachioGuy** [bruvzg/gdsdecomp#58]
I lost the code on my computer for my game but i still have the apk on my phone

**Comment by nikitalita** [comment]
It should be. Extract the APK and get the PAK file from it, then use the CLI (read the README) to recover the project.

**Comment by PistachioGuy** [comment]
There is no .pck file inside of it, the apk looks like this 
![image](https://user-images.githubusercontent.com/88635913/174457015-987824e0-405f-493a-b457-73a48337dfe6.png)

**Comment by nikitalita** [comment]
Can you post the APK? If you don't want to upload it publicly, you can send it to me on Discord, I messaged you.

**Comment by PistachioGuy** [comment]
Sure I'll send on discord.

**Comment by PistachioGuy** [comment]
I needed to extract the apk, make the assets folder into a pck file, and then run the full project recovery on that. Thanks so much for the help nikitalita
