### ISSUE TITLE
Error compiling with 3.1.1-stable in Windows?

### ISSUE THREAD

**Issue by sprite-1** [bruvzg/gdsdecomp#6]
I get the following error when I try to compile the module with the source for 3.1.1-stable

```
scons: Building targets ...
[ 70%] Compiling ==> modules\gdsdecomp\editor\gdre_editor.cpp
gdre_editor.cpp
modules\gdsdecomp\editor\gdre_editor.cpp(24): fatal error C1083: Cannot open include file: 'core/crypto/crypto_core.h': No such file or directory
scons: *** [modules\gdsdecomp\editor\gdre_editor.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

There doesn't seem to be any `crypto` folder inside `core`

**Comment by bruvzg** [comment]
Current master is using 3.2-dev crypto API, commits before 73ab9383 should be compatible with 3.1.1.

**Comment by sprite-1** [comment]
That seems to do the trick! Are you also going to add an option to re-pack the PCK into an executable? ((Basically generate a self-contained executable) or should I open that as a new issue

**Comment by bruvzg** [comment]
PCK embedding is added in 35f6a31fa416ff66098008837fea7a4352c7212d
3.1.x crypto API compatibility is restored in 6baabfda144fb5c90c4612fa7c424fb32138b06a
