### ISSUE TITLE
How do access the CLI?

### ISSUE THREAD

**Issue by Chucnutz** [bruvzg/gdsdecomp#62]
How does one access the Command line interface?

**Comment by nikitalita** [comment]
on windows, this is the command prompt: https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/

**Comment by Chucnutz** [comment]
I think I needed to be a bit more specific, sorry. I need to know the process of actually running GDRE in Command line and decompiling a project. Is it only accessible for the Godot module or is it also available for the standalone?

**Comment by nikitalita** [comment]
Use the standalone binary in releases, use the instructions in the README on how to use the CLI.

**Comment by Chucnutz** [comment]
I can get the binary running using CMD now, I want to perform a full project recovery on a project for example test.pck in the desktop folder.how would I go about it step by step to end up with a test project file? Sorry if I'm being a bit bothersome, I'm just not familiar with using the command line that much.

**Comment by nikitalita** [comment]
It's pretty simple; just extract the gdre_tools windows zip to the same folder as the `test.pak`, then run:
```
gdre_tools.exe --recover=test.pck
```
it should automatically extract to the `test_extracted` folder. `--recover` automatically decompiles all the GDScript code and recovers the project file and the resources.

**Comment by Chucnutz** [comment]
Thanks very much you're a lifesaver
