### ISSUE TITLE
Doesn't work on Swords and Sandals Immortals

### ISSUE THREAD

**Issue by Hinkiii** [bruvzg/gdsdecomp#63]
Fails when extracting the arena backgrounds stex files.
[gdre_export.log](https://github.com/bruvzg/gdsdecomp/files/9486608/gdre_export.log)

**Comment by nikitalita** [comment]
Hmmm, I'm wondering why it's crashing there, that error should be caught and then continue. Is there a free version of this game anywhere?

**Comment by Hinkiii** [comment]
Sadly not a demo is in the works but the game as a whole is early access.

**Comment by nikitalita** [comment]
This is fixed in the latest release: https://github.com/bruvzg/gdsdecomp/releases/tag/v0.0.10
