### ISSUE TITLE
Fix MacOS CI by adding `universal` template export

### ISSUE THREAD

**Issue by nikitalita** [bruvzg/gdsdecomp#68]
Godot project exports for MacOS now require a `universal` export template in order to run natively on ARM macs. I am not sure how to do this with github actions, and it doesn't seem like Godot's github CI does this? @bruvzg , do you know how to compile an arm binary on Github actions?

**Comment by bruvzg** [comment]
ARM binary can be compiled by adding `arch=arm64` to the build command, to make universal one, build both x86_64 and ARM binaries and combine them using `lipo -create x86_binary_name arm_binary_name -output universal_binary_name` command.

**Comment by nikitalita** [comment]
Does Github's CI support this out of the box, or do I have to add packages to support cross-compiling?

**Comment by bruvzg** [comment]
It should be able to build it out of the box.

**Comment by nikitalita** [comment]
That did it, thanks!
Fixed in https://github.com/bruvzg/gdsdecomp/commit/95a8274d2ed38edf462e6cd68593ff271c7b1a9e
