### ISSUE TITLE
closes after starting

### ISSUE THREAD

**Issue by botondmester** [bruvzg/gdsdecomp#69]
i am on win11 and when I start it, first it shows the window, then immediately closes.
Where can I find the log files that I can send in?

**Comment by nikitalita** [comment]
The gui automatically closes due to a bug in the current release. However, you cannot use the gui to do full project recovery, you have to use the CLI, please read the read me.

**Comment by nikitalita** [comment]
Fixed with the new alpha, give it a shot!
