### ISSUE TITLE
Unable to display a full window on a small resolution screen

### ISSUE THREAD

**Issue by Yakumo-Yukari** [bruvzg/gdsdecomp#71]
![1254115](https://user-images.githubusercontent.com/12076232/194470980-022af6c5-1312-495f-858b-2f9e15e03c97.png)

I can't place a small window in Explorer and I can't display the buttons at the bottom.

Can it be fixed?

**Comment by nikitalita** [comment]
This is fixed in the new alpha release, which should drop in the next couple hours (or whenever the CI finishes building).
