### ISSUE TITLE
When the file name is not in English, e.g. Chinese, Japanese, Korean, it will be garbled.

### ISSUE THREAD

**Issue by Yakumo-Yukari** [bruvzg/gdsdecomp#73]
![test](https://user-images.githubusercontent.com/12076232/194682890-a9b668f8-c2ee-4897-8b34-35bbb9c86b76.PNG)
Is there any solution to this problem?

**Comment by nikitalita** [comment]
Hmmm, it's either that we don't have east asian character support in the font that we use with GDRE Tools, or the file names were not UTF-8 encoded. When extracting, are the file names rendered correctly or are they still garbled?

**Comment by Yakumo-Yukari** [comment]
> Hmmm, it's either that we don't have east asian character support in the font that we use with GDRE Tools, or the file names were not UTF-8 encoded. When extracting, are the file names rendered correctly or are they still garbled?

Files can be displayed correctly after being extracted to a folder

**Comment by nikitalita** [comment]
Ah, then it's likely just a font issue. Can you recommend a good open source font that has good support for both Latin characters as well as East Asian characters?

**Comment by Yakumo-Yukari** [comment]
> Ah, then it's likely just a font issue. Can you recommend a good open source font that has good support for both Latin characters as well as East Asian characters?

I'm very sorry, I don't have a better font to recommend either

**Comment by nikitalita** [comment]
That's ok, I found this: https://fonts.google.com/noto/specimen/Noto+Sans/about

Can you supply a sample game that has chinese character names in the files so that I can test his?

**Comment by nikitalita** [comment]
Well, the good news is that including this font does fix the issue; the bad is that it's 33mb in size, it's not really an option to include it.

However, it should just be falling back to the system fonts if it's not able to render a character correctly. @bruvzg , do you know why it wouldn't be using a fallback font here, or do we have to configure those manually? If they have to be configured manually, how would we do that per platform?

**Comment by nikitalita** [comment]
Ok, they apparently have to be configured manually. I’ll whip up a quick hack later today.

**Comment by nikitalita** [comment]
When the CI finishes building, can you download one of the "standalone" artifacts here and see if this fixes your issue? https://github.com/bruvzg/gdsdecomp/actions/runs/3232103113

**Comment by nikitalita** [comment]
Also, let me know what OS you're on (Linux, Windows, etc.)

**Comment by Yakumo-Yukari** [comment]
> Also, let me know what OS you're on (Linux, Windows, etc.)

Windows 10

**Comment by nikitalita** [comment]
Did the standalone windows artifact work for you?

**Comment by Yakumo-Yukari** [comment]
> Did the standalone windows artifact work for you?

Yes, it fits perfectly, now it's just so cool

**Comment by nikitalita** [comment]
Excellent, I shall merge the PR and tag a new release then.
