### ISSUE TITLE
Gui Is not working on windows, CLI is working though

### ISSUE THREAD

**Issue by reynold666** [bruvzg/gdsdecomp#74]
Hi, GUI does not startup for me on clicking on the EXE.  Able to use the CLI command to extract the pck file though.

**Comment by nikitalita** [comment]
Are you using the latest version, 0.4.0? This was a bug in the previous version.

**Comment by reynold666** [comment]
yes. using the latest

**Comment by nikitalita** [comment]
Hmmm, can you post what is output to the terminal when you start it from the CLI with no options? Also, since this is based on Godot 4.x, you will need a Vulkan capable card to start it in GUI mode, check if you have that on your PC.

**Comment by reynold666** [comment]
I got it working after I checked that godot 4 beta 2 also was not working. I am working through a laptop with ryzern iGPU and dedicated GTX 1650 GPU.  The Godot executable was always switching to the Ryzen iGPU so had to disable the same,  Posting the link to help other users who run into the problem:
https://nvidia.custhelp.com/app/answers/detail/a_id/5182/~/unable-to-launch-vulkan-apps%2Fgame-on-notebooks-with-amd-radeon-igpus

**Comment by reynold666** [comment]
Solution posted above. Thanks to author for help provided.

**Comment by nikitalita** [comment]
I’m going to leave this open in case further people encounter this issue; it’s weird that the integrated GPU doesn’t support vulkan.

**Comment by reynold666** [comment]
okay

**Comment by reynold666** [comment]
> 
I didn't bother looking into it more. But I think it's the manufactures that are too lazy to bother addressing it for entry level gaming laptops :(. I think the newer models with Ryzen 5000/6000 series with RTX 3000 series might have it solved already out of the box.
