### ISSUE TITLE
Issue with decompiling

### ISSUE THREAD

**Issue by otDan** [bruvzg/gdsdecomp#75]
currently there is an issue with negative match cases being indented incorrectly, how it is:
![image](https://user-images.githubusercontent.com/59731738/194691392-234863a1-f52a-4a53-81e0-a2d9e8740024.png)
how it should be:
![image](https://user-images.githubusercontent.com/59731738/194691404-e4219f10-4902-4a6a-9bd7-6ccf915b07c3.png)

**Comment by nikitalita** [comment]
When the CI finishes the build action, can you test out the artifacts from the run here to see if that fixes the issue? It should be done in a couple hours at the most: https://github.com/bruvzg/gdsdecomp/actions/runs/3209408790

**Comment by otDan** [comment]
sure

**Comment by otDan** [comment]
yup that version works!
