### ISSUE TITLE
.glb files aren't recovered

### ISSUE THREAD

**Issue by Probablew** [bruvzg/gdsdecomp#77]
When I recover a game, the .glb files are missing from the output folder. Just the .import files are in it

**Comment by nikitalita** [comment]
Yes, recovering the original model/mesh files (glb,fbx,dae,etc.) from scene resources are currently not implemented. I've been thinking about how to do this during project recovery, but it's likely going to take a lot of work. In the meantime, I think you can use the "export to GLTF" functionality in the editor to recover those.

**Comment by Probablew** [comment]
Okay, thanks

**Comment by nikitalita** [comment]
Actually, if you wouldn’t mind, could you send me the project you’re trying to recover? I want to test to see what steps you need to do to recover the glb files. If you want to send it privately, you can hit me up on the Godot discord, I’m  “nikita_lita” on there.
