### ISSUE TITLE
Released binaries unusable in smaller screens

### ISSUE THREAD

**Issue by YeldhamDev** [bruvzg/gdsdecomp#8]
The bottom buttons on dialogs are completely hidden if the screen happens to be small (e. g. 1366x768), this could be solved by having their minimal sizes to be smaller.

**Comment by bruvzg** [comment]
Should be fixed in bfbb9e3 (and [v0.0.7](https://github.com/bruvzg/gdsdecomp/releases/tag/v0.0.7) release).
