### ISSUE TITLE
Getting Started - Linux

### ISSUE THREAD

**Issue by ririmudev** [bruvzg/gdsdecomp#9]
Greetings,

It's not quite clear from the README how to get started as a godot newbie (on linux).  I messed around by checking out the 3.2 branch here, and downloaded a few versions of godot (3.2.2 stable - headless&server&x11; 3.1 stable - headless&server; 3.1-beta6 - x11; and a local scons build of 3.2.2 stable).  Wasn't able to get a functioning version under any of those on Ubuntu 16.04.7 (kernel 4.15.0-115-generic).  I assumed one of the above would satisfy the requirements for Godot 3.x, but no dice.

I figured it would be possible to run with something like:
`bin/godot_server.x11.tools.64 --path ~/dev/gdsdecomp/standalone`

But that's where I get errors such as
`ERROR: is_class_enabled: Cannot get class 'GodotREEditorStandalone'.`
` At: core/class_db.cpp:1329.`

Or, if I ran:
` ~/Downloads/godot/Godot_v3.2.2-stable_linux_server.64 ~/dev/gdsdecomp/standalone/project.godot`
Then I'd get:
`ERROR: is_class_enabled: Condition "!ti" is true. Returned: false`
` At: core/class_db.cpp:1329.`

Note: for the godot executable (which shall remain nameless) I'm looking into, I was able to successfully do the README sections for "To detect Godot version" and "To detect GDScript version"

Any attention and/or tips would be appreciated.  Thanks
~ririmudev

**Comment by bruvzg** [comment]
Main part of it is a C++ module, you can't just use the project with unmodified Godot version. Instead, you should download and extract Godot engine source, clone this repo into the `modules/gdsdecomp` folder and rebuild the engine (see: https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html).

**Comment by ririmudev** [comment]
Much thanks for the prompt response.  Any chance known working versions (OS and godot) could be mentioned?  I tried the build with the `modules/gdsdecomp` folder using my same Ubuntu 16 and godot 3.2.2 stable, but I'm now getting:
`ERROR: move_child: Parent node is busy setting up children, move_child() failed. Consider using call_deferred("move_child") instead (or "popup" if this is from a popup)`

I'll see what I can do to resolve my build issues, but just to ask for dummies: if it builds successfully, what would one run to know that it's setup and working correctly?  Would `${GODOT_DIR}/bin/godot_server.x11.tools.64 --path ~/dev/gdsdecomp/standalone` work, or something else?

**Comment by ririmudev** [comment]
Much thanks for the prompt response. Any chance known working versions (OS, graphics driver, and godot) could be mentioned? I tried the build with the modules/gdsdecomp folder using my same Ubuntu 16 and godot 3.2.2 stable, but I'm now getting:
ERROR: move_child: Parent node is busy setting up children, move_child() failed. Consider using call_deferred("move_child") instead (or "popup" if this is from a popup)

I'll see what I can do to resolve my build issues, but just to ask for dummies: if it builds successfully, what would one run to know that it's setup and working correctly? Would ${GODOT_DIR}/bin/godot_server.x11.tools.64 --path ~/dev/gdsdecomp/standalone work, or something else?

(edit - accidentally deleted)
