### ISSUE TITLE
Scripts have two spaces between "onready" and "var"

### ISSUE THREAD

**Issue by BryceBarbara** [bruvzg/gdsdecomp#92]
Not sure if this is intended or not but it seems accidental.

![image](https://user-images.githubusercontent.com/24460210/201254314-6a35c34b-74bf-44a5-b7a7-28927e71e659.png)

**Comment by nikitalita** [comment]
It is not. Can you try the "standalone" artifacts here after the CI finishes building? https://github.com/bruvzg/gdsdecomp/actions/runs/3450118772

**Comment by nikitalita** [comment]
use this one, the previous one had errors: https://github.com/bruvzg/gdsdecomp/actions/runs/3453027624
