### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by Smokeyey** [bruvzg/gdsdecomp#95]
So, when I attempt to start the decompiler, it opens a new window that is entirely blank-white. The icon is the default one, there is no text at the top labeling the window, and then it shuts down after a few seconds.
After a lot of pain, since I am not an expert at this sort of thing, I found crash dumps for failed attempts at opening the decompiler. These crash dumps can be provided if needed, but I feel the most pertinent info is the error code and the bit of text explaining it.
0xC0000005
The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
I've looked up both of these, found stuff that didn't really help. Once again, not an expert, so while what I found probably works, I cannot make it work as is. I'm not smart enough or have the general capability.

**Comment by nikitalita** [comment]
It sounds it might be related to issue #74 ; try the instructions that reynold mentions here: https://github.com/bruvzg/gdsdecomp/issues/74#issuecomment-1272253601

**Comment by Smokeyey** [comment]
I did notice that and did follow the solution found there; didn't work. No noticeable change.

**Comment by nikitalita** [comment]
Can you start it from the command line and paste the output from the terminal?

**Comment by Smokeyey** [comment]
The output is a mess; many many lines that are just plain identical. I'll try to find all the unique ones.
ERROR: Error (-3) creating shader module for stage: Compute
   at: (drivers\vulkan\rendering_device_vulkan.cpp:5561)
ERROR: Condition "!shader" is true. Returning: RID()
   at: RenderingDeviceVulkan::compute_pipeline_create (drivers\vulkan\rendering_device_vulkan.cpp:6906)
ERROR: Condition "!shader" is true. Returning: RID()
   at: RenderingDeviceVulkan::uniform_set_create (drivers\vulkan\rendering_device_vulkan.cpp:5804)
ERROR: Condition "!particles_storage->particles_shader.shader.version_is_valid(version)" is true.
   at: RendererRD::ParticlesStorage::ParticlesShaderData::set_code (servers\rendering\renderer_rd\storage_rd\particles_storage.cpp:1589)
ERROR: Condition "p_shader.is_null()" is true.
   at: PipelineCacheRD::setup (servers\rendering\renderer_rd\pipeline_cache_rd.cpp:89)
ERROR: Condition "!shader" is true. Returning: RID()
   at: RenderingDeviceVulkan::render_pipeline_create (drivers\vulkan\rendering_device_vulkan.cpp:6438)
ERROR: Condition "!canvas_singleton->shader.canvas_shader.version_is_valid(version)" is true.
   at: RendererCanvasRenderRD::CanvasShaderData::set_code (servers\rendering\renderer_rd\renderer_canvas_render_rd.cpp:2063)
ERROR: Attempted to name invalid ID: 0
   at: RenderingDeviceVulkan::set_resource_name (drivers\vulkan\rendering_device_vulkan.cpp:8900)
ERROR: Condition "!scene_singleton->sky.sky_shader.shader.version_is_valid(version)" is true.
   at: RendererRD::SkyRD::SkyShaderData::set_code (servers\rendering\renderer_rd\environment\sky.cpp:131)
ERROR: Condition "!fog_singleton->volumetric_fog.shader.version_is_valid(version)" is true.
   at: RendererRD::Fog::FogShaderData::set_code (servers\rendering\renderer_rd\environment\fog.cpp:358)

I think that's all of them.

**Comment by nikitalita** [comment]
It looks like your video card doesn't support compute shaders. Can you post your specs and OS?

**Comment by Smokeyey** [comment]
Processor	AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Windows 10
I removed the device name, device id, and product id, assuming they aren't needed and are personal.

**Comment by nikitalita** [comment]
No graphics card?

**Comment by nikitalita** [comment]
3700X does not have integrated graphics, so you should have a separate video card.

**Comment by nikitalita** [comment]
Ok, so you actually have the exact same setup as me (3700x, RX5700, 32GB RAM, Windows 10), so you definitely should not have issues with compiling those shaders. This may be a driver issue; I'd recommend updating, and if that doesn't work, reinstall the drivers.

**Comment by Smokeyey** [comment]
Which drivers should I reinstall in specific?

**Comment by nikitalita** [comment]
The radeon drivers: https://www.amd.com/en/support/graphics/amd-radeon-5700-series/amd-radeon-rx-5700-series/amd-radeon-rx-5700

**Comment by Smokeyey** [comment]
It worked. I could kiss you.

Let this be a reminder to all: get new drivers.

**Comment by slmarcos** [comment]
I had the same issue with NVidia Drivers with the most recent version of Ubuntu 22. I needed to downgrade to version 510 to fix it.
